### ISSUE TITLE
Irrtümlich gelöschte SKOS-Konzepte ergänzen

### ISSUE THREAD

**Issue by acka47** [hbz/lbz-vocabs#9]
Aus RPB-207:

> Mit Commit [098d9a93298a2b1d24061eadd5fb23293013391a](https://github.com/hbz/lbz-vocabs/commit/098d9a93298a2b1d24061eadd5fb23293013391a) zur Ergänzung der Raumsystematikpfade ([RPB-146](https://jira.hbz-nrw.de/browse/RPB-146)) ist folgendes passiert:
> - Durch die Ergänzung der Pfad-Strings hat die Datei die maximale Größe überschritten, mit der die Inhalte noch auf GitHub angezeigt und bearbeitet werden können.
> - Einige SKOS-Konzepte sind offenbar verschwunden. Der diff zu diesem Commit ist nicht besonders informativ, so dass sich nicht auf einem Blick die fehlenden Konzepte ablesen lassen. Ich kann aber sagen, wieviele entfernt wurden: Vor dem Commit waren es 10589 Konzepte, danach 10567. Es müssten also insgesamt 22 Konzepte fehlen.

Ein Vergleich der Code-Stände vor und nach dem Commit zeigt, dass folgende 22 Konzepte entfernt wurden:

```
https://rpb.lobid.org/spatial#n35
https://rpb.lobid.org/spatial#n4004655n2
https://rpb.lobid.org/spatial#n4010909n4
https://rpb.lobid.org/spatial#n4012733n3
https://rpb.lobid.org/spatial#n4054837n5
https://rpb.lobid.org/spatial#n4055608n6
https://rpb.lobid.org/spatial#n4060881n5
https://rpb.lobid.org/spatial#n4101955n6
https://rpb.lobid.org/spatial#n4108577n2
https://rpb.lobid.org/spatial#n4110084n0
https://rpb.lobid.org/spatial#n4115441n1
https://rpb.lobid.org/spatial#n4133948n4
https://rpb.lobid.org/spatial#n4329692n0
https://rpb.lobid.org/spatial#n4377902n5
https://rpb.lobid.org/spatial#n4393883n8
https://rpb.lobid.org/spatial#n4639983n5
https://rpb.lobid.org/spatial#n4653560n3
https://rpb.lobid.org/spatial#n4678434n2
https://rpb.lobid.org/spatial#n47
https://rpb.lobid.org/spatial#n4827033n7
https://rpb.lobid.org/spatial#n54
https://rpb.lobid.org/spatial#n92
```

@fsteeg Soll ich die einfach manuell wieder reinkopieren oder wie gehen wir am besten vor?

**Comment by fsteeg** [comment]
Hm, haben wir irgendwo dokumentiert, wie die Datei erzeugt wurde / wird?

Der Commit hier verweist ja auf https://github.com/hbz/rpb/commit/daa60f2, dadurch sollten ja keine Konzepte rausfliegen.

**Comment by acka47** [comment]
Wir haben gerade in einerm Zweier-Treffen folgende Lösung besprochen: Ich werde die fehlenden Konzepte manuell ergänzen und @fsteeg dann die Strapi-Daten für den Lookup aktualisieren.
